# Generated by Django 5.0.6 on 2024-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="referrer_id",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="default1", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
