# Generated by Django 5.0.6 on 2024-09-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InstagramDjangoApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagramaccount",
            name="followers",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="following",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="total_followers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="total_following",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="trial_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="subscription_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free_trial", "Free Trial"),
                    ("basic", "Basic"),
                    ("medium", "Medium"),
                    ("premium", "Premium"),
                    ("unsubscribed", "Unsubscribed"),
                ],
                default="unsubscribed",
                max_length=50,
                null=True,
            ),
        ),
    ]
