# Generated by Django 5.0.6 on 2024-09-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InstagramDjangoApp", "0003_instagramaccount_impression_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagramaccount",
            name="followers_1_day_ago",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="followers_2_days_ago",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="followers_3_days_ago",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="following_1_day_ago",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="following_2_days_ago",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="following_3_days_ago",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagramaccount",
            name="is_business_account",
            field=models.BooleanField(default=False),
        ),
    ]
