# Generated by Django 5.0.7 on 2024-08-09 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramDjangoApp', '0003_remove_instagramaccount_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stripe_customer_id',
            new_name='paystack_customer_id',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='reference',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('medium', 'Medium'), ('premium', 'Premium'), ('unsubscribed', 'Unsubscribed')], default='unsubscribed', max_length=50, null=True),
        ),
    ]
